### ISSUE TITLE
Error when import the file

### ISSUE THREAD

**Issue by Chelsea-yy** [mwdavis2/ApE#3]
I used the windor version. When I attempted to import the .gb file, it shows this and cracks down.
![Quicker_20240919_201214](https://github.com/user-attachments/assets/75dee7b4-ec5d-4923-acce-ae205b43aea2)
 Could anyone help me solve this problem?

**Comment by mwdavis2** [comment]
This doesn't look like a standard ApE error on Windows? 
Can you post an example file that caused this error? 
Are you using "File>Open" or double clicking a file in the OS?

**Comment by Chelsea-yy** [comment]
> This doesn't look like a standard ApE error on Windows? Can you post an example file that caused this error? Are you using "File>Open" or double clicking a file in the OS?

I used  the "File>Open" to import the file.
The header looks like
![image](https://github.com/user-attachments/assets/d19e49b3-9265-423d-981c-37652e528dbc)

And the feature looks like
![image](https://github.com/user-attachments/assets/d0ade913-bfbf-4998-a0ff-d14a9134cb7b)

and the origin looks like
![image](https://github.com/user-attachments/assets/cb4c80d3-f692-4f8a-acf2-963f52ce7af0)

Is there any problem with the format?

**Comment by mwdavis2** [comment]
No problem with the format.
Looks like you're trying to view a massive genomic section of ch12 (27Mbp). I think earlier versions of ApE could handle this on some computers, but I've added more elaborate display functions at the expense of taking more memory. It's NOT meant as a genome browser, and YMMV if you try to open gigantic, non-plasmid sequences. In this case, you ran out of memory.

**Comment by Chelsea-yy** [comment]
I got it. By the way, could you provide the website for installing the earlier version? I can not find it. Thanks a lot.

**Comment by mwdavis2** [comment]
https://jorgensen.biology.utah.edu/wayned/ape/Download/

**Comment by Chelsea-yy** [comment]
Thanks a lot. It solves.
